package com.example.test

object Global {
    var BLUETOOTH_CONNET_REQUEST_CODE = 1001
    var BLUETOOTH_REQUEST_CODE = 1002
    var DISOVERABLE_REQUEST_CODE = 1003
    var ACTION_REQUEST_ENABLE_REQUEST_CODE = 1004
    var ACCESS_COARSE_LOCATION_REQUEST_CODE = 1005
}
